#!/usr/bin/env node

'use strict';

const { main } = require('./index.js');

main()
    .catch(err => {
        console.error(`Failed with error:`);
        console.error(err && err.stack || err);
        process.exit(1);
    });